[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
p2p_exchange = "AqSnWdAnJgdnHzXpUApk9ctPUhaLiikNrrgecbm3YH2k"

[programs.devnet]
p2p_exchange = "AqSnWdAnJgdnHzXpUApk9ctPUhaLiikNrrgecbm3YH2k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"
members = ["programs/p2p-exchange"]