[build]
  command = "npm run netlify-build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
